package Employee;

import DatabaseUtil.DBconnect;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.control.MenuItem;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import Employee.EmployeeController;
import javafx.stage.Stage;

public class editEmployeeController {
    private EmployeeData data;
    private DBconnect dc;

    @FXML
    private TextField Username;
    @FXML
    private PasswordField password;
    @FXML
    private MenuItem selectManager;
    @FXML
    private MenuItem selectWorker;
    @FXML
    private TextField PositionInput;
    @FXML
    private TextField PhoneNumInput;
    @FXML
    private Button cancelButton;
    @FXML
    private Button SaveButton;

    public void initdata(EmployeeData data){
        Username.setText(data.getUsername());
        password.setText(data.getPassword());
        PhoneNumInput.setText(data.getPhonenum());
        PositionInput.setText(data.getPosition());
        this.data = data;
    }



    // Event Listener on Button[#cancelButton].onAction
    @FXML
    public void Cancel(ActionEvent event) throws IOException {
        try{
            Stage employeestage = new Stage();

            FXMLLoader EmpLoader = new FXMLLoader(getClass().getResource("/Employee/employee.fxml"));
            Parent root = EmpLoader.load();
            EmployeeController employeeController = EmpLoader.getController();
            employeeController.loadEmpDataFunc();
            Scene scene1 = new Scene(root);

            //Employee Scene
            employeestage.setScene(scene1);
            employeestage.setTitle("Employee Dashboard");
            employeestage.setResizable(false);
            employeestage.show();

        }catch(IOException e){
            e.printStackTrace();
        }
    }
    // Event Listener on Button[#SaveButton].onAction
    @FXML
    public void Save(ActionEvent event) {

        try{
            String update = "UPDATE employee SET username= '" + Username.getText() + "', password = '" + password.getText() + "', Position = '" + PositionInput.getText() + "', phoneNumber = '" + PhoneNumInput.getText() + "' WHERE username = '" + Username.getText() + "' " ;

            Connection con = dc.getConnection();
            PreparedStatement stnt = con.prepareStatement(update);


            stnt.execute();
            con.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
        // TODO Autogenerated
    }
}
